// Mocks generated by Mockito 5.4.6 from annotations
// in university_health_center/test/unit/features/reviews/submit_review_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:university_health_center/features/reviews/data/repositories/review_repository.dart'
    as _i2;
import 'package:university_health_center/features/reviews/domain/models/review.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ReviewRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReviewRepository extends _i1.Mock implements _i2.ReviewRepository {
  MockReviewRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> submitReview(_i4.Review? review) =>
      (super.noSuchMethod(
            Invocation.method(#submitReview, [review]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Review>> getDoctorReviews(String? doctorId) =>
      (super.noSuchMethod(
            Invocation.method(#getDoctorReviews, [doctorId]),
            returnValue: _i3.Future<List<_i4.Review>>.value(<_i4.Review>[]),
          )
          as _i3.Future<List<_i4.Review>>);

  @override
  _i3.Future<_i4.Review?> getReviewByAppointment(String? appointmentId) =>
      (super.noSuchMethod(
            Invocation.method(#getReviewByAppointment, [appointmentId]),
            returnValue: _i3.Future<_i4.Review?>.value(),
          )
          as _i3.Future<_i4.Review?>);

  @override
  _i3.Future<void> updateReview(
    String? reviewId,
    int? newRating,
    String? newReviewText,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReview, [
              reviewId,
              newRating,
              newReviewText,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteReview(String? reviewId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReview, [reviewId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
