// Mocks generated by Mockito 5.4.6 from annotations
// in university_health_center/test/widget/features/profile/accessibility_settings_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:university_health_center/features/profile/presentation/pages/accessibility_settings_page.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AccessibilityProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessibilityProvider extends _i1.Mock
    implements _i2.AccessibilityProvider {
  MockAccessibilityProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get highContrastMode =>
      (super.noSuchMethod(
            Invocation.getter(#highContrastMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get largeTextMode =>
      (super.noSuchMethod(Invocation.getter(#largeTextMode), returnValue: false)
          as bool);

  @override
  bool get reduceAnimations =>
      (super.noSuchMethod(
            Invocation.getter(#reduceAnimations),
            returnValue: false,
          )
          as bool);

  @override
  bool get screenReaderOptimized =>
      (super.noSuchMethod(
            Invocation.getter(#screenReaderOptimized),
            returnValue: false,
          )
          as bool);

  @override
  double get textScaleFactor =>
      (super.noSuchMethod(Invocation.getter(#textScaleFactor), returnValue: 0.0)
          as double);

  @override
  Duration get animationDuration =>
      (super.noSuchMethod(
            Invocation.getter(#animationDuration),
            returnValue: _FakeDuration_0(
              this,
              Invocation.getter(#animationDuration),
            ),
          )
          as Duration);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateSettings({
    required bool? highContrastMode,
    required bool? largeTextMode,
    required bool? reduceAnimations,
    required bool? screenReaderOptimized,
    required double? textScaleFactor,
  }) => super.noSuchMethod(
    Invocation.method(#updateSettings, [], {
      #highContrastMode: highContrastMode,
      #largeTextMode: largeTextMode,
      #reduceAnimations: reduceAnimations,
      #screenReaderOptimized: screenReaderOptimized,
      #textScaleFactor: textScaleFactor,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
