// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDca03QEyLDedfIqWe9kK4nSacXVyD0ui4',
    appId: '1:728817514552:web:649e69ec6d10492afb4ecd',
    messagingSenderId: '728817514552',
    projectId: 'university-health-center-6cc98',
    authDomain: 'university-health-center-6cc98.firebaseapp.com',
    databaseURL:
        'https://university-health-center-6cc98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'university-health-center-6cc98.firebasestorage.app',
    measurementId: 'G-V6P4N97X7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeuscZ1KaY7yq7LazB-R3upStFbnZ2z7o',
    appId: '1:728817514552:android:f53a9ade0ec2009afb4ecd',
    messagingSenderId: '728817514552',
    projectId: 'university-health-center-6cc98',
    databaseURL:
        'https://university-health-center-6cc98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'university-health-center-6cc98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2a5aNtRthfHJ9YHip6DqENpFcO4hxnqg',
    appId: '1:728817514552:ios:f438f51317281db5fb4ecd',
    messagingSenderId: '728817514552',
    projectId: 'university-health-center-6cc98',
    databaseURL:
        'https://university-health-center-6cc98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'university-health-center-6cc98.firebasestorage.app',
    iosBundleId: 'com.example.universityHealthCenter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2a5aNtRthfHJ9YHip6DqENpFcO4hxnqg',
    appId: '1:728817514552:ios:f438f51317281db5fb4ecd',
    messagingSenderId: '728817514552',
    projectId: 'university-health-center-6cc98',
    databaseURL:
        'https://university-health-center-6cc98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'university-health-center-6cc98.firebasestorage.app',
    iosBundleId: 'com.example.universityHealthCenter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDca03QEyLDedfIqWe9kK4nSacXVyD0ui4',
    appId: '1:728817514552:web:78931c69d65eef6ffb4ecd',
    messagingSenderId: '728817514552',
    projectId: 'university-health-center-6cc98',
    authDomain: 'university-health-center-6cc98.firebaseapp.com',
    databaseURL:
        'https://university-health-center-6cc98-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'university-health-center-6cc98.firebasestorage.app',
    measurementId: 'G-161DZ3PBS4',
  );
}
